services:
  entertainment-tracker-api:
    container_name: entertainment-tracker-api
    build:
      context: .
      dockerfile: EntertainmentTracker.Api/Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
    cpus: 0.5
    mem_limit: 1g
    restart: unless-stopped
    init: true
    security_opt:
      - no-new-privileges:true
    environment:
      ASPNETCORE_URLS: "https://+:5000"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "${HTTPS_CERTIFICATE_PASSWORD}"
    volumes:
      - ./secrets/rsa:/secrets/rsa:ro
      - ./secrets/certs:/https:ro